[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "ef03cdac77d72d89366410058552d871549c0262"
libgfortran_version = "5.0.0"
os = "macos"

    [[Algencan.download]]
    sha256 = "2763a54b6d9fb7ed40a701eff2fb63f3fa721dfef6d8b42cf15b1764da6e4123"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "c90fe018c8e93a3522541c1c23a1457b9860a106"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "1e3dfae9556b0ee84ab3d2720895dd59b6605c4e49c873443084d765b2ceea90"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "519cc8907d3eb21dd066909b39a876d14f732ab1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "0eed7d4e50184059d3346196a5db45d3f3f23e76ede29593cfd9b6fbebd80adf"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "13d35fda799e4913673123989cbc45281062c87a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Algencan.download]]
    sha256 = "f442b284014b003774e03a5eba82632ea6bda1d35ea16971b56914713c8722fc"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8699d04cf6e0c80300fd9b2737862715890244ae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "04067b2eaf8ad2a184495b81bdea35c6e1a213b920dfa90d3a0e0ea064496d86"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "906014aae4fe5d1da8b7f1c93f5fead8e55a5eda"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "59dd102986da4d67143300e264ab05ad2c80c6d9222c7edddfc845df72dbe533"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe423f14404134dc8280916e90ae0bdff0bf3b24"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "7601c0b6f1707055d17bb59ec0345c2b9b7bc38ab0544588398d3aab7d08cc06"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f97bc3b7b52f03913bb34139764f0ddad3c3337b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "93dfa6f06d9869248665a242654adfb5bee8202b8654987171483fc29c8ef19c"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "i686"
git-tree-sha1 = "2fef4c63ee4a4006ee8a9d0e605468a923cecd80"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "dc3f38e4ef830cfe0e8046a5e55dad7e0db4788c189e341ac8acd1c11048eca1"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.i686-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "i686"
git-tree-sha1 = "8bfb4d761bd5c209c0a8d1bbb782dc3a34d8a6b3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "b1704f94c6be228569b71040697f840f14f51599b21762872713476120743acf"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.i686-linux-musl-libgfortran5.tar.gz"
[[Algencan]]
arch = "i686"
git-tree-sha1 = "c155c3a9eb3146444428f5c4c99850ecb1a8a097"
libgfortran_version = "5.0.0"
os = "windows"

    [[Algencan.download]]
    sha256 = "9ad0a46770f99a1cdd91eb4dea2d21abf99a9d8c8b51773f42de480eb202ad1d"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[Algencan]]
arch = "powerpc64le"
git-tree-sha1 = "1c9b0b0bc5a59379435577a683e8fe2f7c70af62"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "b4dd53b7fa9805f56fa4569256172fef06fff15c71b8f974970be968de86e4b1"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "riscv64"
git-tree-sha1 = "a975cf6c2752b8d0ab41f327eb750aa0c9b1fa9c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "b8290a3d9b99f9f83b4811be34106fbbce8f2bdcfcecf5569147cf759ad86a2a"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.riscv64-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "a095e5e818f7d26eb4af405dadecb3a50fc9d22c"
libgfortran_version = "5.0.0"
os = "macos"

    [[Algencan.download]]
    sha256 = "c6699aac379eb678181079a69e5c3ea04d59f3eaab340b6aea1afcf30dbf17f3"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "2258ece8ad0113697c5d4aaae1f71bc647390c19"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "8adb6e16c047ecb8f643cd2c2034d7e680d7a005c26042baba0222974be93ce4"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "0e03f909adc83b909245293863e6608c42c15434"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "b0be0eb921053fbbb60b38bc83f94d4d48232d6e1e249a8b4ed47f00023e4c3f"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "984f8fb9ed76f9db277dba6c8d789ea19d15ea3c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Algencan.download]]
    sha256 = "7b0e2ab7f65692d869161b006472db3b0ba2efb6b94ce2d92fc974265b378f74"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "76ec470848a982583e7a31bb27db7c4cddeed3c5"
libgfortran_version = "5.0.0"
os = "windows"

    [[Algencan.download]]
    sha256 = "ba13b0eb0e308966ac86dd749992a7cdcbf0f3783a3b3b24c6b7c868061f183f"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.2+0/Algencan.v3.1.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
