[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "4966ec74a786d6f4e56594b9d67744c9d9673ea1"
libgfortran_version = "5.0.0"
os = "macos"

    [[Algencan.download]]
    sha256 = "8e9b265569409df39470725219796d64d1a45d5f9c2524ae19acd2ee5a34fbd7"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "a463dd6cd5ec4a871af77d22ee2bca35ca3015cd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "09301fa1179ecc2a6af2e2673335cc9668bed5ca1fa204d0af8d11210c62669d"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "7c69cc1fba0055a8dc9d89ac07d4a9bf867b0693"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "c2e659e67f5e525baaecfb97117caca6b5eaa476c4d68da73b16cf0b4cbdc9ef"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Algencan]]
arch = "aarch64"
git-tree-sha1 = "54dee479014f994f32732c148fb120ccad824762"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Algencan.download]]
    sha256 = "707895b8df3f566437c2d008af216cca83c7ea0a969e0bb0253e2e4d834811ee"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57902349b850fbd34ddb8b4598bea0fd17bafe65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "3e3b2f0fd518ba9f02ec87d107c80de86c0c1701430b768e4a52cb476143685a"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8eb42d0b3eeaa1bb07f63a9b36de8a625806d38b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "3b6fd268d48869080d836ae210fab5842488f17a0a46652981807315be9e71b6"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "822e905903b63b1aee57742db6b7f061763a741a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "411a523f2a2667affd20c901f74d0669937d50e23ea255c1700494a78930896a"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c312343cdcff5be4e256fc43fe2eb7d280b9e24c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "cbd8ec998e317c286d499ed7a69f15ca9d1cf083c66cb8027f496f270897faa6"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Algencan]]
arch = "i686"
git-tree-sha1 = "cb6cc3ad1a6561ee6a69aac6f89e5b6a7a4edad3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "c30406419f22ebfe404c650b3b36776c4ea1ab35c4e7f2b4ae5bfcf297aca76b"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "i686"
git-tree-sha1 = "6a47ef34480d3503b3d3ea810b4dda2937c0c6ca"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "edfee875eb31b492e35fb49ba1089d0003cfeb290bbb1d6c852912134a508652"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.i686-linux-musl-libgfortran5.tar.gz"
[[Algencan]]
arch = "i686"
git-tree-sha1 = "216509d69e6b177a1fa48d7172d3ee8c8e95afd6"
libgfortran_version = "5.0.0"
os = "windows"

    [[Algencan.download]]
    sha256 = "a23c727223391463dcc84cb1ed1208d7df422b017e5b2e3c7d20fb81b4cf1a1d"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Algencan]]
arch = "powerpc64le"
git-tree-sha1 = "06efabaa9b0a80b8f7f758d53588a284c1ebb8fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "698a1639d590ffb3362cb49f189f0ada2961f98638d4a76c617e165da41fd0fb"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "riscv64"
git-tree-sha1 = "9335cdbbb2495046b5d10395b2ada0c3ef1b9151"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "ded364baae2ef67e83dc4958b8d7803ce2f1c56cc736f57e6e25a538b16e089d"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "d9093a65915c22559b9d49b8045fb326726c28ec"
libgfortran_version = "5.0.0"
os = "macos"

    [[Algencan.download]]
    sha256 = "71ad6a8aa7a7d51f128d69fafd6d80212ee7168e993826b1abe5e6a6f5fb8c4f"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "55b585a19bdf8cf506a7d2129b8adae885176259"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "6c772b83924e0af6ce02c7502d8b58ffe33abd58101ac6a72956cc4f2606ff2f"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "9de324f12ab956ebbceeb30ba3af52763289c0ca"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Algencan.download]]
    sha256 = "eee84a88e38669a708af273fa2ce7dbafb450066de4862b6bb923636a347fdd1"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "fa2434881a2e0a46907755afeaf1a081d9da8395"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Algencan.download]]
    sha256 = "f632dc392cef0e7cc8d02e550fab4c4fc307c3b9225314069a6cd7e3035466d9"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Algencan]]
arch = "x86_64"
git-tree-sha1 = "49807fa56ca50002b6062ae52f128df21e1ef9bc"
libgfortran_version = "5.0.0"
os = "windows"

    [[Algencan.download]]
    sha256 = "696ab0fe24b0ac700189187761148569e46f5b445927f6d8747f67da1fd478b2"
    url = "https://github.com/JuliaBinaryWrappers/Algencan_jll.jl/releases/download/Algencan-v3.1.1+1/Algencan.v3.1.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
