# Autogenerated wrapper script for Algencan_jll for i686-linux-musl-libgfortran5
export libalgencan

using CompilerSupportLibraries_jll
using HSL_jll
JLLWrappers.@generate_wrapper_header("Algencan")
JLLWrappers.@declare_library_product(libalgencan, "libalgencan.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, HSL_jll)
    JLLWrappers.@init_library_product(
        libalgencan,
        "lib/libalgencan.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
