# Autogenerated wrapper script for Algencan_jll for x86_64-w64-mingw32-libgfortran5
export libalgencan

using CompilerSupportLibraries_jll
using HSL_jll
JLLWrappers.@generate_wrapper_header("Algencan")
JLLWrappers.@declare_library_product(libalgencan, "libalgencan.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, HSL_jll)
    JLLWrappers.@init_library_product(
        libalgencan,
        "bin\\libalgencan.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
